# Generated by Django 5.2.2 on 2026-09-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0002_datatreinamento_pergunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='data_treinamento',
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='documento',
            field=models.FileField(upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='data_treinamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
